"""The SPC700 instruction set: what each opcode is, and how it reads back.

Two views of the same 256 entries. `OPCODES` gives an instruction, an addressing
mode and a length, which is what an interpreter dispatches on. `TEXT` gives the
assembler form, which is what a listing prints.

The bit indexed instructions collapse into one entry each. `SET1`, `CLR1`, `BBS`
and `BBC` occupy sixteen opcodes apiece and differ only in which bit they touch,
and that bit is the top three bits of the opcode, so carrying eight near
identical mnemonics would put the same information in two places.
"""

import collections

from .errors import Truncated

Instruction = collections.namedtuple("Instruction", "address size text opcode mnemonic mode")

RETURNS = frozenset({"ret", "reti"})


OPCODES = (
    ("nop", "implied", 1),
    ("tcall", "tcall", 1),
    ("set1", "dp_bit", 2),
    ("bbs", "dp_bit_rel", 3),
    ("or", "a_dp", 2),
    ("or", "a_abs", 3),
    ("or", "a_ix", 1),
    ("or", "a_idx", 2),
    ("or", "a_imm", 2),
    ("or", "dp_dp", 3),
    ("or1", "c_membit", 3),
    ("asl", "dp", 2),
    ("asl", "abs", 3),
    ("push", "p", 1),
    ("tset", "abs_a", 3),
    ("brk", "implied", 1),
    ("bpl", "rel", 2),
    ("tcall", "tcall", 1),
    ("clr1", "dp_bit", 2),
    ("bbc", "dp_bit_rel", 3),
    ("or", "a_dpx", 2),
    ("or", "a_absx", 3),
    ("or", "a_absy", 3),
    ("or", "a_idy", 2),
    ("or", "dp_imm", 3),
    ("or", "ix_iy", 1),
    ("decw", "dp", 2),
    ("asl", "dpx", 2),
    ("asl", "a", 1),
    ("dec", "x", 1),
    ("cmp", "x_abs", 3),
    ("jmp", "abs_indirect_x", 3),
    ("clrp", "implied", 1),
    ("tcall", "tcall", 1),
    ("set1", "dp_bit", 2),
    ("bbs", "dp_bit_rel", 3),
    ("and", "a_dp", 2),
    ("and", "a_abs", 3),
    ("and", "a_ix", 1),
    ("and", "a_idx", 2),
    ("and", "a_imm", 2),
    ("and", "dp_dp", 3),
    ("or1", "c_notmembit", 3),
    ("rol", "dp", 2),
    ("rol", "abs", 3),
    ("push", "a", 1),
    ("cbne", "dp_rel", 3),
    ("bra", "rel", 2),
    ("bmi", "rel", 2),
    ("tcall", "tcall", 1),
    ("clr1", "dp_bit", 2),
    ("bbc", "dp_bit_rel", 3),
    ("and", "a_dpx", 2),
    ("and", "a_absx", 3),
    ("and", "a_absy", 3),
    ("and", "a_idy", 2),
    ("and", "dp_imm", 3),
    ("and", "ix_iy", 1),
    ("incw", "dp", 2),
    ("rol", "dpx", 2),
    ("rol", "a", 1),
    ("inc", "x", 1),
    ("cmp", "x_dp", 2),
    ("call", "abs", 3),
    ("setp", "implied", 1),
    ("tcall", "tcall", 1),
    ("set1", "dp_bit", 2),
    ("bbs", "dp_bit_rel", 3),
    ("eor", "a_dp", 2),
    ("eor", "a_abs", 3),
    ("eor", "a_ix", 1),
    ("eor", "a_idx", 2),
    ("eor", "a_imm", 2),
    ("eor", "dp_dp", 3),
    ("and1", "c_membit", 3),
    ("lsr", "dp", 2),
    ("lsr", "abs", 3),
    ("push", "x", 1),
    ("tclr", "abs_a", 3),
    ("pcall", "pcall", 2),
    ("bvc", "rel", 2),
    ("tcall", "tcall", 1),
    ("clr1", "dp_bit", 2),
    ("bbc", "dp_bit_rel", 3),
    ("eor", "a_dpx", 2),
    ("eor", "a_absx", 3),
    ("eor", "a_absy", 3),
    ("eor", "a_idy", 2),
    ("eor", "dp_imm", 3),
    ("eor", "ix_iy", 1),
    ("cmpw", "ya_dp", 2),
    ("lsr", "dpx", 2),
    ("lsr", "a", 1),
    ("mov", "x_a", 1),
    ("cmp", "y_abs", 3),
    ("jmp", "abs", 3),
    ("clrc", "implied", 1),
    ("tcall", "tcall", 1),
    ("set1", "dp_bit", 2),
    ("bbs", "dp_bit_rel", 3),
    ("cmp", "a_dp", 2),
    ("cmp", "a_abs", 3),
    ("cmp", "a_ix", 1),
    ("cmp", "a_idx", 2),
    ("cmp", "a_imm", 2),
    ("cmp", "dp_dp", 3),
    ("and1", "c_notmembit", 3),
    ("ror", "dp", 2),
    ("ror", "abs", 3),
    ("push", "y", 1),
    ("dbnz", "dp_rel", 3),
    ("ret", "implied", 1),
    ("bvs", "rel", 2),
    ("tcall", "tcall", 1),
    ("clr1", "dp_bit", 2),
    ("bbc", "dp_bit_rel", 3),
    ("cmp", "a_dpx", 2),
    ("cmp", "a_absx", 3),
    ("cmp", "a_absy", 3),
    ("cmp", "a_idy", 2),
    ("cmp", "dp_imm", 3),
    ("cmp", "ix_iy", 1),
    ("addw", "ya_dp", 2),
    ("ror", "dpx", 2),
    ("ror", "a", 1),
    ("mov", "a_x", 1),
    ("cmp", "y_dp", 2),
    ("reti", "implied", 1),
    ("setc", "implied", 1),
    ("tcall", "tcall", 1),
    ("set1", "dp_bit", 2),
    ("bbs", "dp_bit_rel", 3),
    ("adc", "a_dp", 2),
    ("adc", "a_abs", 3),
    ("adc", "a_ix", 1),
    ("adc", "a_idx", 2),
    ("adc", "a_imm", 2),
    ("adc", "dp_dp", 3),
    ("eor1", "c_membit", 3),
    ("dec", "dp", 2),
    ("dec", "abs", 3),
    ("mov", "y_imm", 2),
    ("pop", "p", 1),
    ("mov", "dp_imm", 3),
    ("bcc", "rel", 2),
    ("tcall", "tcall", 1),
    ("clr1", "dp_bit", 2),
    ("bbc", "dp_bit_rel", 3),
    ("adc", "a_dpx", 2),
    ("adc", "a_absx", 3),
    ("adc", "a_absy", 3),
    ("adc", "a_idy", 2),
    ("adc", "dp_imm", 3),
    ("adc", "ix_iy", 1),
    ("subw", "ya_dp", 2),
    ("dec", "dpx", 2),
    ("dec", "a", 1),
    ("mov", "x_sp", 1),
    ("div", "ya_x", 1),
    ("xcn", "a", 1),
    ("ei", "implied", 1),
    ("tcall", "tcall", 1),
    ("set1", "dp_bit", 2),
    ("bbs", "dp_bit_rel", 3),
    ("sbc", "a_dp", 2),
    ("sbc", "a_abs", 3),
    ("sbc", "a_ix", 1),
    ("sbc", "a_idx", 2),
    ("sbc", "a_imm", 2),
    ("sbc", "dp_dp", 3),
    ("mov1", "c_membit", 3),
    ("inc", "dp", 2),
    ("inc", "abs", 3),
    ("cmp", "y_imm", 2),
    ("pop", "a", 1),
    ("mov", "ixinc_a", 1),
    ("bcs", "rel", 2),
    ("tcall", "tcall", 1),
    ("clr1", "dp_bit", 2),
    ("bbc", "dp_bit_rel", 3),
    ("sbc", "a_dpx", 2),
    ("sbc", "a_absx", 3),
    ("sbc", "a_absy", 3),
    ("sbc", "a_idy", 2),
    ("sbc", "dp_imm", 3),
    ("sbc", "ix_iy", 1),
    ("movw", "ya_dp", 2),
    ("inc", "dpx", 2),
    ("inc", "a", 1),
    ("mov", "sp_x", 1),
    ("das", "a", 1),
    ("mov", "a_ixinc", 1),
    ("di", "implied", 1),
    ("tcall", "tcall", 1),
    ("set1", "dp_bit", 2),
    ("bbs", "dp_bit_rel", 3),
    ("mov", "dp_a", 2),
    ("mov", "abs_a", 3),
    ("mov", "ix_a", 1),
    ("mov", "idx_a", 2),
    ("cmp", "x_imm", 2),
    ("mov", "abs_x", 3),
    ("mov1", "membit_c", 3),
    ("mov", "dp_y", 2),
    ("mov", "abs_y", 3),
    ("mov", "x_imm", 2),
    ("pop", "x", 1),
    ("mul", "ya", 1),
    ("bne", "rel", 2),
    ("tcall", "tcall", 1),
    ("clr1", "dp_bit", 2),
    ("bbc", "dp_bit_rel", 3),
    ("mov", "dpx_a", 2),
    ("mov", "absx_a", 3),
    ("mov", "absy_a", 3),
    ("mov", "idy_a", 2),
    ("mov", "dp_x", 2),
    ("mov", "dpy_x", 2),
    ("movw", "dp_ya", 2),
    ("mov", "dpx_y", 2),
    ("dec", "y", 1),
    ("mov", "a_y", 1),
    ("cbne", "dpx_rel", 3),
    ("daa", "a", 1),
    ("clrv", "implied", 1),
    ("tcall", "tcall", 1),
    ("set1", "dp_bit", 2),
    ("bbs", "dp_bit_rel", 3),
    ("mov", "a_dp", 2),
    ("mov", "a_abs", 3),
    ("mov", "a_ix", 1),
    ("mov", "a_idx", 2),
    ("mov", "a_imm", 2),
    ("mov", "x_abs", 3),
    ("not1", "c_membit", 3),
    ("mov", "y_dp", 2),
    ("mov", "y_abs", 3),
    ("notc", "implied", 1),
    ("pop", "y", 1),
    ("sleep", "implied", 1),
    ("beq", "rel", 2),
    ("tcall", "tcall", 1),
    ("clr1", "dp_bit", 2),
    ("bbc", "dp_bit_rel", 3),
    ("mov", "a_dpx", 2),
    ("mov", "a_absx", 3),
    ("mov", "a_absy", 3),
    ("mov", "a_idy", 2),
    ("mov", "x_dp", 2),
    ("mov", "x_dpy", 2),
    ("mov", "dp_dp", 3),
    ("mov", "y_dpx", 2),
    ("inc", "y", 1),
    ("mov", "y_a", 1),
    ("dbnz", "y_rel", 2),
    ("stop", "implied", 1),
)

TEXT = (
    "nop",
    "tcall 0",
    "set0 ${dp0}",
    "bbs0 ${dp0},${rel3}",
    "or a,${dp0}",
    "or a,${abs}",
    "or a,(x)",
    "or a,(${dp0}+x)",
    "or a,#${op0}",
    "or ${dp1},${dp0}",
    "or1 c,${mem}:{bit}",
    "asl ${dp0}",
    "asl ${abs}",
    "push p",
    "tset ${abs},a",
    "brk",
    "bpl ${rel2}",
    "tcall 1",
    "clr0 ${dp0}",
    "bbc0 ${dp0},${rel3}",
    "or a,${dp0}+x",
    "or a,${abs}+x",
    "or a,${abs}+y",
    "or a,(${dp0})+y",
    "or ${dp1},#${op0}",
    "or (x),(y)",
    "decw ${dp0}",
    "asl ${dp0}+x",
    "asl a",
    "dec x",
    "cmp x,${abs}",
    "jmp (${abs}+x)",
    "clrp",
    "tcall 2",
    "set1 ${dp0}",
    "bbs1 ${dp0},${rel3}",
    "and a,${dp0}",
    "and a,${abs}",
    "and a,(x)",
    "and a,(${dp0}+x)",
    "and a,#${op0}",
    "and ${dp1},${dp0}",
    "or1 c,!${mem}:{bit}",
    "rol ${dp0}",
    "rol ${abs}",
    "push a",
    "cbne ${dp0},${rel3}",
    "bra ${rel2}",
    "bmi ${rel2}",
    "tcall 3",
    "clr1 ${dp0}",
    "bbc1 ${dp0},${rel3}",
    "and a,${dp0}+x",
    "and a,${abs}+x",
    "and a,${abs}+y",
    "and a,(${dp0})+y",
    "and ${dp1},#${op0}",
    "and (x),(y)",
    "incw ${dp0}",
    "rol ${dp0}+x",
    "rol a",
    "inc x",
    "cmp x,${dp0}",
    "call ${abs}",
    "setp",
    "tcall 4",
    "set2 ${dp0}",
    "bbs2 ${dp0},${rel3}",
    "eor a,${dp0}",
    "eor a,${abs}",
    "eor a,(x)",
    "eor a,(${dp0}+x)",
    "eor a,#${op0}",
    "eor ${dp1},${dp0}",
    "and1 c,${mem}:{bit}",
    "lsr ${dp0}",
    "lsr ${abs}",
    "push x",
    "tclr ${abs},a",
    "pcall $ff{op0}",
    "bvc ${rel2}",
    "tcall 5",
    "clr2 ${dp0}",
    "bbc2 ${dp0},${rel3}",
    "eor a,${dp0}+x",
    "eor a,${abs}+x",
    "eor a,${abs}+y",
    "eor a,(${dp0})+y",
    "eor ${dp1},#${op0}",
    "eor (x),(y)",
    "cmpw ya,${dp0}",
    "lsr ${dp0}+x",
    "lsr a",
    "mov x,a",
    "cmp y,${abs}",
    "jmp ${abs}",
    "clrc",
    "tcall 6",
    "set3 ${dp0}",
    "bbs3 ${dp0},${rel3}",
    "cmp a,${dp0}",
    "cmp a,${abs}",
    "cmp a,(x)",
    "cmp a,(${dp0}+x)",
    "cmp a,#${op0}",
    "cmp ${dp1},${dp0}",
    "and1 c,!${mem}:{bit}",
    "ror ${dp0}",
    "ror ${abs}",
    "push y",
    "dbnz ${dp0},${rel3}",
    "ret",
    "bvs ${rel2}",
    "tcall 7",
    "clr3 ${dp0}",
    "bbc3 ${dp0},${rel3}",
    "cmp a,${dp0}+x",
    "cmp a,${abs}+x",
    "cmp a,${abs}+y",
    "cmp a,(${dp0})+y",
    "cmp ${dp1},#${op0}",
    "cmp (x),(y)",
    "addw ya,${dp0}",
    "ror ${dp0}+x",
    "ror a",
    "mov a,x",
    "cmp y,${dp0}",
    "reti",
    "setc",
    "tcall 8",
    "set4 ${dp0}",
    "bbs4 ${dp0},${rel3}",
    "adc a,${dp0}",
    "adc a,${abs}",
    "adc a,(x)",
    "adc a,(${dp0}+x)",
    "adc a,#${op0}",
    "adc ${dp1},${dp0}",
    "eor1 c,${mem}:{bit}",
    "dec ${dp0}",
    "dec ${abs}",
    "mov y,#${op0}",
    "pop p",
    "mov ${dp1},#${op0}",
    "bcc ${rel2}",
    "tcall 9",
    "clr4 ${dp0}",
    "bbc4 ${dp0},${rel3}",
    "adc a,${dp0}+x",
    "adc a,${abs}+x",
    "adc a,${abs}+y",
    "adc a,(${dp0})+y",
    "adc ${dp1},#${op0}",
    "adc (x),(y)",
    "subw ya,${dp0}",
    "dec ${dp0}+x",
    "dec a",
    "mov x,sp",
    "div ya,x",
    "xcn a",
    "ei",
    "tcall 10",
    "set5 ${dp0}",
    "bbs5 ${dp0},${rel3}",
    "sbc a,${dp0}",
    "sbc a,${abs}",
    "sbc a,(x)",
    "sbc a,(${dp0}+x)",
    "sbc a,#${op0}",
    "sbc ${dp1},${dp0}",
    "mov1 c,${mem}:{bit}",
    "inc ${dp0}",
    "inc ${abs}",
    "cmp y,#${op0}",
    "pop a",
    "mov (x)+,a",
    "bcs ${rel2}",
    "tcall 11",
    "clr5 ${dp0}",
    "bbc5 ${dp0},${rel3}",
    "sbc a,${dp0}+x",
    "sbc a,${abs}+x",
    "sbc a,${abs}+y",
    "sbc a,(${dp0})+y",
    "sbc ${dp1},#${op0}",
    "sbc (x),(y)",
    "movw ya,${dp0}",
    "inc ${dp0}+x",
    "inc a",
    "mov sp,x",
    "das a",
    "mov a,(x)+",
    "di",
    "tcall 12",
    "set6 ${dp0}",
    "bbs6 ${dp0},${rel3}",
    "mov ${dp0},a",
    "mov ${abs},a",
    "mov (x),a",
    "mov (${dp0}+x),a",
    "cmp x,#${op0}",
    "mov ${abs},x",
    "mov1 ${mem}:{bit},c",
    "mov ${dp0},y",
    "mov ${abs},y",
    "mov x,#${op0}",
    "pop x",
    "mul ya",
    "bne ${rel2}",
    "tcall 13",
    "clr6 ${dp0}",
    "bbc6 ${dp0},${rel3}",
    "mov ${dp0}+x,a",
    "mov ${abs}+x,a",
    "mov ${abs}+y,a",
    "mov (${dp0})+y,a",
    "mov ${dp0},x",
    "mov ${dp0}+y,x",
    "movw ${dp0},ya",
    "mov ${dp0}+x,y",
    "dec y",
    "mov a,y",
    "cbne ${dp0}+x,${rel3}",
    "daa a",
    "clrv",
    "tcall 14",
    "set7 ${dp0}",
    "bbs7 ${dp0},${rel3}",
    "mov a,${dp0}",
    "mov a,${abs}",
    "mov a,(x)",
    "mov a,(${dp0}+x)",
    "mov a,#${op0}",
    "mov x,${abs}",
    "not1 c,${mem}:{bit}",
    "mov y,${dp0}",
    "mov y,${abs}",
    "notc",
    "pop y",
    "sleep",
    "beq ${rel2}",
    "tcall 15",
    "clr7 ${dp0}",
    "bbc7 ${dp0},${rel3}",
    "mov a,${dp0}+x",
    "mov a,${abs}+x",
    "mov a,${abs}+y",
    "mov a,(${dp0})+y",
    "mov x,${dp0}",
    "mov x,${dp0}+y",
    "mov ${dp1},${dp0}",
    "mov y,${dp0}+x",
    "inc y",
    "mov y,a",
    "dbnz y,${rel2}",
    "stop",
)


def bit_index(opcode: int) -> int:
    """Which bit a SET1, CLR1, BBS or BBC opcode acts on."""
    return opcode >> 5


def call_index(opcode: int) -> int:
    """Which entry of the call table a TCALL opcode jumps through."""
    return opcode >> 4


def _signed(value: int) -> int:
    return value - 0x100 if value >= 0x80 else value


def _fields(data: bytes | bytearray, offset: int, address: int, p: int) -> dict[str, str]:
    first = data[offset + 1] if offset + 1 < len(data) else 0
    second = data[offset + 2] if offset + 2 < len(data) else 0
    absolute = first | (second << 8)
    return {
        "op0": f"{first:02x}",
        "op1": f"{second:02x}",
        "dp0": f"{(p << 8) | first:03x}",
        "dp1": f"{(p << 8) | second:03x}",
        "abs": f"{absolute:04x}",
        "mem": f"{absolute & 0x1FFF:04x}",
        "bit": f"{absolute >> 13:d}",
        "rel2": f"{(address + 2 + _signed(first)) & 0xFFFF:04x}",
        "rel3": f"{(address + 3 + _signed(second)) & 0xFFFF:04x}",
    }


def decode(data: bytes | bytearray, offset: int, address: int, p: int = 0) -> Instruction:
    """One instruction, or `Truncated` when the bytes run out mid instruction."""
    if offset >= len(data):
        raise Truncated(f"offset {offset} is past the end of {len(data)} bytes")
    opcode = data[offset]
    mnemonic, mode, size = OPCODES[opcode]
    if offset + size > len(data):
        raise Truncated(
            f"opcode {opcode:02X} at {offset} needs {size} bytes, {len(data) - offset} remain"
        )
    return Instruction(
        address=address,
        size=size,
        text=TEXT[opcode].format(**_fields(data, offset, address, p)),
        opcode=opcode,
        mnemonic=mnemonic,
        mode=mode,
    )


def disassemble(
    data: bytes | bytearray,
    offset: int,
    address: int,
    count: int | None = None,
    p: int = 0,
    stop_at_return: bool = False,
) -> list[Instruction]:
    """A listing, stopping at the count, at a return, or where the bytes end."""
    listing: list[Instruction] = []
    while count is None or len(listing) < count:
        try:
            instruction = decode(data, offset, address, p)
        except Truncated:
            break
        listing.append(instruction)
        offset += instruction.size
        address = (address + instruction.size) & 0xFFFF
        if stop_at_return and instruction.mnemonic in RETURNS:
            break
    return listing
